[env:esp32-s]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI@^2.5.0

build_flags =
    -I src
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_WIDTH=76
    -DTFT_HEIGHT=284
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_CS=17
    -DTFT_DC=4
    -DTFT_RST=16
    -DTFT_BL=32
    -DTFT_BACKLIGHT_ON=HIGH
    -DSPI_FREQUENCY=20000000
